name: dhwa
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pytz
  - h5py
  - jinja2
  - joblib
  - networkx
  - sympy
  - setuptools
  - wheel 
  - pip:
      - torch==2.5.1
      - snntorch==0.9.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.17.0
      - fonttools==4.55.4
      - fsspec==2024.12.0
      - h5py==3.12.1
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - nir==1.0.4
      - nirtorch==1.0
      - numpy==2.2.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
